CC=gcc
CFLAGS=-std=c99 -MMD
LIB=-lmingw32 -lglfw3dll -lopengl32 -lfreetype6
DEPS=globals.h graphics.h deferredrenderer.h shader.h input.h camera.h model.h material.h light.h text.h lobj.h exploration.h
OBJ=globals.o main.o graphics.o deferredrenderer.o shader.o input.o camera.o model.o material.o light.o text.o glew.o exploration.o

all: a

main.o: main.c
	$(CC) $(CFLAGS) -c $^
glew.o: glew.c
	$(CC) $(CFLAGS) -c $^
globals.o: globals.c globals.h
	$(CC) $(CFLAGS) -c $^
graphics.o: graphics.c graphics.h lobj.h
	$(CC) $(CFLAGS) -c $^
deferredrenderer.o: deferredrenderer.c deferredrenderer.h
	$(CC) $(CFLAGS) -c $^
shader.o: shader.c shader.h
	$(CC) $(CFLAGS) -c $^
input.o: input.c input.h
	$(CC) $(CFLAGS) -c $^
camera.o: camera.c camera.h
	$(CC) $(CFLAGS) -c $^
model.o: model.c model.h
	$(CC) $(CFLAGS) -c $^
material.o: material.c material.h
	$(CC) $(CFLAGS) -c $^
light.o: light.c light.h
	$(CC) $(CFLAGS) -c $^
text.o: text.c text.h
	$(CC) $(CFLAGS) -c $^

exploration.o: exploration.c exploration.h
	$(CC) $(CFLAGS) -c $^

.PHONY: a clean
a: $(OBJ)
	$(CC) $(CFLAGS) -o builds/$@ $^ $(LIB)
clean:
	-del edit *.o